"""add gallery photo points and soft delete

Revision ID: 3d88548564e0
Revises: d29b275f7c6b
Create Date: 2026-09-21 00:09:02.783003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d88548564e0'
down_revision: Union[str, Sequence[str], None] = 'd29b275f7c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleryphotopoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('gallery_photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleryphotopoints_gallery_photo_id'), 'galleryphotopoints', ['gallery_photo_id'], unique=True)
    op.create_index(op.f('ix_galleryphotopoints_submitted_by_user_id'), 'galleryphotopoints', ['submitted_by_user_id'], unique=False)
    op.add_column(
        'galleryphoto',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('galleryphoto', 'is_deleted', server_default=None)
    op.create_index(op.f('ix_galleryphoto_is_deleted'), 'galleryphoto', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_galleryphoto_is_deleted'), table_name='galleryphoto')
    op.drop_column('galleryphoto', 'is_deleted')
    op.drop_index(op.f('ix_galleryphotopoints_submitted_by_user_id'), table_name='galleryphotopoints')
    op.drop_index(op.f('ix_galleryphotopoints_gallery_photo_id'), table_name='galleryphotopoints')
    op.drop_table('galleryphotopoints')
    # ### end Alembic commands ###
