"""baseline schema

Revision ID: b11fde67a1dd
Revises: 
Create Date: 2026-08-08 15:56:38.498410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b11fde67a1dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chair_role', sa.Enum('member', 'nonmember', 'president', 'vpe', 'vpi', 'treasurer', 'secretary', 'comm_director', 'regional_rep', 'new_member_rep', 'dir_int_aff', 'marketing_chair', 'mentorshpe_chair', 'academic_chair', 'professional_chair', 'career_fair_chair', 'web_dev_chair', 'social_chair', 'shpe_jr_chair', 'outreach_chair', 'eec_chair', 'shpetina_chair', 'athletic_chair', 'projects_chair', 'member_relations_chair', name='role'), nullable=True),
    sa.Column('joinable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_row_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sign_in_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sign_out_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sign_in_code'), 'event', ['sign_in_code'], unique=True)
    op.create_index(op.f('ix_event_sign_out_code'), 'event', ['sign_out_code'], unique=True)
    op.create_index(op.f('ix_event_source_row_id'), 'event', ['source_row_id'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('apparel', 'item', name='producttype'), nullable=False),
    sa.Column('sizes', sa.JSON(), nullable=True),
    sa.Column('image_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolereport',
    sa.Column('role', sa.Enum('member', 'nonmember', 'president', 'vpe', 'vpi', 'treasurer', 'secretary', 'comm_director', 'regional_rep', 'new_member_rep', 'dir_int_aff', 'marketing_chair', 'mentorshpe_chair', 'academic_chair', 'professional_chair', 'career_fair_chair', 'web_dev_chair', 'social_chair', 'shpe_jr_chair', 'outreach_chair', 'eec_chair', 'shpetina_chair', 'athletic_chair', 'projects_chair', 'member_relations_chair', name='role'), nullable=False),
    sa.Column('supervisor_role', sa.Enum('member', 'nonmember', 'president', 'vpe', 'vpi', 'treasurer', 'secretary', 'comm_director', 'regional_rep', 'new_member_rep', 'dir_int_aff', 'marketing_chair', 'mentorshpe_chair', 'academic_chair', 'professional_chair', 'career_fair_chair', 'web_dev_chair', 'social_chair', 'shpe_jr_chair', 'outreach_chair', 'eec_chair', 'shpetina_chair', 'athletic_chair', 'projects_chair', 'member_relations_chair', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('shopsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_item_cap', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cougarnet_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personal_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_num', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('psid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', 'not_say', 'other', name='gender'), nullable=False),
    sa.Column('first_gen', sa.Boolean(), nullable=False),
    sa.Column('college', sa.Enum('nsm', 'engineering', 'cot', 'other', name='colleges'), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sa.Enum('freshman', 'sophomore', 'junior', 'senior', 'graduate', name='classification'), nullable=False),
    sa.Column('gpa', sa.Enum('gpa_350_400', 'gpa_300_349', 'gpa_250_299', 'gpa_below_249', 'no_gpa', name='gpa'), nullable=True),
    sa.Column('exp_grad_date', sa.Enum('fall_2026', 'spring_2027', 'fall_2027', 'spring_2028', 'fall_2028', 'spring_2029', 'fall_2029', 'spring_2030', 'fall_2030', 'spring_2031', 'other', name='expgraddate'), nullable=False),
    sa.Column('in_slack', sa.Boolean(), nullable=False),
    sa.Column('is_returning', sa.Enum('new', 'returning_1', 'returning_2', 'returning_3_plus', name='membershipstatus'), nullable=False),
    sa.Column('is_national_member', sa.Boolean(), nullable=False),
    sa.Column('shirt_size', sa.Enum('s', 'm', 'l', 'xl', 'xxl', 'other', name='shirtsize'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('member', 'nonmember', 'president', 'vpe', 'vpi', 'treasurer', 'secretary', 'comm_director', 'regional_rep', 'new_member_rep', 'dir_int_aff', 'marketing_chair', 'mentorshpe_chair', 'academic_chair', 'professional_chair', 'career_fair_chair', 'web_dev_chair', 'social_chair', 'shpe_jr_chair', 'outreach_chair', 'eec_chair', 'shpetina_chair', 'athletic_chair', 'projects_chair', 'member_relations_chair', name='role'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('resume_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resume_drive_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cougarnet_email'), 'user', ['cougarnet_email'], unique=True)
    op.create_index(op.f('ix_user_personal_email'), 'user', ['personal_email'], unique=True)
    op.create_index(op.f('ix_user_psid'), 'user', ['psid'], unique=True)
    op.create_table('committee_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committeemembership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('is_chair', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'committee_id')
    )
    op.create_table('emailverificationtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailverificationtoken_token_hash'), 'emailverificationtoken', ['token_hash'], unique=False)
    op.create_index(op.f('ix_emailverificationtoken_user_id'), 'emailverificationtoken', ['user_id'], unique=False)
    op.create_table('eventattendance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('signed_in_at', sa.DateTime(), nullable=False),
    sa.Column('signed_out_at', sa.DateTime(), nullable=True),
    sa.Column('brought_new_member', sa.Boolean(), nullable=False),
    sa.Column('new_member_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('eventhost',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'committee_id')
    )
    op.create_index(op.f('ix_eventhost_committee_id'), 'eventhost', ['committee_id'], unique=False)
    op.create_table('eventreminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventreminder_event_id'), 'eventreminder', ['event_id'], unique=False)
    op.create_index(op.f('ix_eventreminder_user_id'), 'eventreminder', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('paid', 'ready', 'picked_up', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('square_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_code'), 'order', ['order_code'], unique=True)
    op.create_table('passwordresettoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_token_hash'), 'passwordresettoken', ['token_hash'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('user_country_origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interested_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interested_industry', sa.Enum('aerospace', 'agriculture', 'automotive', 'chemical_plant', 'construction', 'consulting', 'cosmetics', 'cybersecurity', 'defense', 'electronics', 'environmental', 'lab_research', 'manufacturing', 'medical_devices', 'oil_and_gas', 'pharmaceuticals', 'semiconductors', 'supply_chain', 'transportation', 'other', name='industry'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_prof_dev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prof_dev', sa.Enum('internships', 'full_time', 'research', 'other', name='profdev'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_race_ethnicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_and_ethnicity', sa.Enum('native_american', 'asian', 'black', 'hispanic', 'pacific_islander', 'white', 'multiracial', 'other', name='raceethnicity'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('user_race_ethnicity')
    op.drop_table('user_prof_dev')
    op.drop_table('user_interested_industries')
    op.drop_table('user_country_origin')
    op.drop_index(op.f('ix_passwordresettoken_user_id'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_token_hash'), table_name='passwordresettoken')
    op.drop_table('passwordresettoken')
    op.drop_index(op.f('ix_order_order_code'), table_name='order')
    op.drop_table('order')
    op.drop_table('notification')
    op.drop_index(op.f('ix_eventreminder_user_id'), table_name='eventreminder')
    op.drop_index(op.f('ix_eventreminder_event_id'), table_name='eventreminder')
    op.drop_table('eventreminder')
    op.drop_index(op.f('ix_eventhost_committee_id'), table_name='eventhost')
    op.drop_table('eventhost')
    op.drop_table('eventattendance')
    op.drop_index(op.f('ix_emailverificationtoken_user_id'), table_name='emailverificationtoken')
    op.drop_index(op.f('ix_emailverificationtoken_token_hash'), table_name='emailverificationtoken')
    op.drop_table('emailverificationtoken')
    op.drop_table('committeemembership')
    op.drop_table('committee_message')
    op.drop_index(op.f('ix_user_psid'), table_name='user')
    op.drop_index(op.f('ix_user_personal_email'), table_name='user')
    op.drop_index(op.f('ix_user_cougarnet_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('shopsettings')
    op.drop_table('rolereport')
    op.drop_table('product')
    op.drop_index(op.f('ix_event_source_row_id'), table_name='event')
    op.drop_index(op.f('ix_event_sign_out_code'), table_name='event')
    op.drop_index(op.f('ix_event_sign_in_code'), table_name='event')
    op.drop_table('event')
    op.drop_table('committee')
    # ### end Alembic commands ###
