"""add gallery photo submissions

Revision ID: d29b275f7c6b
Revises: e5b8c3d0f421
Create Date: 2026-09-19 00:26:06.553145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd29b275f7c6b'
down_revision: Union[str, Sequence[str], None] = 'e5b8c3d0f421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleryphoto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('semester', sa.Enum('fall', 'spring', name='semester'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='galleryphotostatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleryphoto_reviewed_by_user_id'), 'galleryphoto', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_galleryphoto_submitted_by_user_id'), 'galleryphoto', ['submitted_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_galleryphoto_submitted_by_user_id'), table_name='galleryphoto')
    op.drop_index(op.f('ix_galleryphoto_reviewed_by_user_id'), table_name='galleryphoto')
    op.drop_table('galleryphoto')
    op.execute("DROP TYPE galleryphotostatus")
    op.execute("DROP TYPE semester")
    # ### end Alembic commands ###
